"""
Build 01_References/As_Builts/INDEX.md from index.json.

index.json is the single source of truth for the page -> sheet mapping. Claude
fills it after viewing each render; a human ticks `verified` after checking.
INDEX.md is generated — never hand-edit it.

index.json schema (list of objects):
    {
      "pdf_page": 1,                 # int, 1-based, required
      "sheet_no": "1",               # str or null if not a numbered sheet
      "title": "GENERAL PLAN",       # str, as lettered on the sheet
      "dwg_no": "…",                 # str or null (USACE drawing/file number)
      "scale": "1\"=20'",            # str or null
      "summary": "…",               # str, what the sheet shows, 1-3 sentences
      "legibility": "good|fair|poor",
      "verified": false,             # bool, human check
      "notes": ""                    # optional
    }

Usage:
    .venv\\Scripts\\python tools\\read-asbuilt\\build_index.py [--index PATH] [--out PATH] [--page-count N]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ASBUILT_DIR = os.path.join(PROJECT_ROOT, "01_References", "As_Builts")
DEFAULT_INDEX = os.path.join(ASBUILT_DIR, "index.json")
DEFAULT_OUT = os.path.join(ASBUILT_DIR, "INDEX.md")

REQUIRED = {"pdf_page": int, "title": str, "summary": str, "legibility": str, "verified": bool}
OPTIONAL = {"sheet_no": (str, type(None)), "dwg_no": (str, type(None)),
            "scale": (str, type(None)), "notes": str}
LEGIBILITY = {"good", "fair", "poor"}


def validate(entries: list[dict]) -> None:
    if not isinstance(entries, list):
        raise ValueError("index.json must be a list")
    seen_pages: set[int] = set()
    for i, e in enumerate(entries):
        if not isinstance(e, dict):
            raise ValueError(f"entry {i} is not an object")
        for k, t in REQUIRED.items():
            if k not in e:
                raise ValueError(f"entry {i} missing required key '{k}'")
            if not isinstance(e[k], t) or (t is int and isinstance(e[k], bool)):
                raise ValueError(f"entry {i} key '{k}' must be {t.__name__}")
        for k, t in OPTIONAL.items():
            if k in e and not isinstance(e[k], t):
                raise ValueError(f"entry {i} key '{k}' has wrong type")
        unknown = set(e) - set(REQUIRED) - set(OPTIONAL)
        if unknown:
            raise ValueError(f"entry {i} has unknown keys {sorted(unknown)}")
        if e["legibility"] not in LEGIBILITY:
            raise ValueError(f"entry {i} legibility must be one of {sorted(LEGIBILITY)}")
        if e["pdf_page"] < 1:
            raise ValueError(f"entry {i} pdf_page must be >= 1")
        if e["pdf_page"] in seen_pages:
            raise ValueError(f"duplicate pdf_page {e['pdf_page']}")
        seen_pages.add(e["pdf_page"])


def _cell(v) -> str:
    if v is None or v == "":
        return "—"
    return str(v).replace("|", "\\|").replace("\n", " ")


def render_markdown(entries: list[dict], page_count: int | None) -> str:
    entries = sorted(entries, key=lambda e: e["pdf_page"])
    lines = [
        "# As-Built Sheet Index — Fruitvale Avenue Highway Bridge (Miller-Sweeney)",
        "",
        f"Generated {date.today().isoformat()} by `tools/read-asbuilt/build_index.py` from `index.json`. "
        "Do not edit this file; edit `index.json` and rerun.",
        "",
        "Source PDF: `01A Fruitvale Avenue Highway Bridge AS-BUILT-1.pdf` (scanned, no text layer). "
        "Renders in `renders/pNNN.png`. Cite as `AS-BUILT Sheet <sheet_no> (PDF p <pdf_page>)`.",
        "",
    ]
    n_ver = sum(1 for e in entries if e["verified"])
    lines.append(f"Indexed pages: {len(entries)}" + (f" of {page_count}" if page_count else "") +
                 f". Human-verified: {n_ver}.")
    lines.append("")
    lines.append("| PDF p | Sheet | Title | Dwg no. | Scale | Legibility | Verified | Summary |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for e in entries:
        lines.append("| " + " | ".join([
            str(e["pdf_page"]), _cell(e.get("sheet_no")), _cell(e["title"]), _cell(e.get("dwg_no")),
            _cell(e.get("scale")), e["legibility"], "yes" if e["verified"] else "no", _cell(e["summary"]),
        ]) + " |")
    notes = [(e["pdf_page"], e["notes"]) for e in entries if e.get("notes")]
    if notes:
        lines += ["", "## Notes", ""]
        lines += [f"- PDF p {p}: {n}" for p, n in notes]
    if page_count:
        indexed = {e["pdf_page"] for e in entries}
        missing = [p for p in range(1, page_count + 1) if p not in indexed]
        lines += ["", "## Pages not yet indexed", ""]
        lines.append(", ".join(str(p) for p in missing) if missing else "None.")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--index", default=DEFAULT_INDEX)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--page-count", type=int, default=None)
    args = ap.parse_args(argv)
    try:
        with open(args.index, encoding="utf-8") as f:
            entries = json.load(f)
        validate(entries)
        md = render_markdown(entries, args.page_count)
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(md)
        print(json.dumps({"status": "ok", "entries": len(entries), "out": args.out}))
        return 0
    except Exception as e:  # noqa: BLE001 — CLI boundary
        print(json.dumps({"status": "error", "message": f"{type(e).__name__}: {e}"}))
        return 1


if __name__ == "__main__":
    sys.exit(main())
